### ISSUE TITLE
Phishing vulnerability

### ISSUE THREAD

**Issue by mangoplane** [Web3Auth/web3auth-unreal-sdk#9]
Hi,

The client seems vulnerable to phishing. What is stopping someone from copying the clientId from the game client, e.g. `BAwFgL-r7wzQKmtcdiz2uHJKNZdK7gzEf2q-m55xfzSZOw8jLOyIi4AVvvzaEQO5nv2dFLEmf9LBkF8kaq3aErg`, and using that to imitate the client in another game that they release.

From there, unsuspecting users would sign-in to the app thinking it's another app, where the session keys are then used for malicious signing of TX to remove funds from the app with clientId `BAwFgL-r7wzQKmtcdiz2uHJKNZdK7gzEf2q-m55xfzSZOw8jLOyIi4AVvvzaEQO5nv2dFLEmf9LBkF8kaq3aErg`.

Kind regards.

**Comment by yashovardhan** [comment]
This is not a vulnerability. All OAuth application generally work with whitelisting strategies. If you're looking for a secure backlinking, you can use secure app links rather than deep links. Our dashboard supports both. check this: https://stackoverflow.com/questions/46169025/android-deep-links-and-app-links-confused
